import {referenceFields,referenceIssues,emptyReference} from './budget-references';
import { z } from 'zod';
export const money=z.string().regex(/^\d{1,9}(\.\d{1,2})?$/,'ใช้จำนวนเงินไม่ติดลบ ไม่เกิน 999,999,999.99 บาท และทศนิยม 2 ตำแหน่ง');
export const cents=(value:string)=>{if(!money.safeParse(value).success)return 0;const [a,b='']=value.split('.');return Number(a)*100+Number(b.padEnd(2,'0'));};
export const baht=(value:number)=>(value/100).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
const text=z.string().trim().max(500).default('');
export const budgetLineSchema=z.object({...referenceFields,id:z.string().uuid(),department:text,plan:text,work:text,fund:text,category:text,type:text,item:text,allocated:money,remaining:money,amount:money,newItem:z.boolean().default(false),investment:z.boolean().default(false),scopeChanged:z.boolean().default(false),purpose:z.string().max(3000).default(''),specification:z.string().max(8000).default('')});
export const budgetSchema=z.object({title:z.string().trim().min(1).max(200),year:z.number().int().min(2500).max(2700),date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>{const d=new Date(v);return !isNaN(+d)&&d.toISOString().slice(0,10)===v;},'วันที่ไม่ถูกต้อง'),organization:text,department:text,phone:text,number:text,recipient:text,signer:text,position:text,background:z.string().max(5000),reason:z.string().max(10000),legalNotes:z.string().max(6000).default(''),proposal:z.string().max(3000).default(''),authority:z.enum(['verify','executive','council']).default('verify'),authorityChecked:z.boolean().default(false),numeralStyle:z.enum(['thai','arabic','original']).default('thai'),decreases:z.array(budgetLineSchema).min(1).max(20),increases:z.array(budgetLineSchema).min(1).max(20),opinions:z.array(z.object({title:text,name:text,position:text,comment:z.string().max(3000).default('')})).max(5).default([])});
export type Budget=z.infer<typeof budgetSchema>;
export type BudgetLine=z.infer<typeof budgetLineSchema>;
export type BudgetRecord={id:string;version:number;updatedAt:string;data:Budget;documentId:string|null};
export const budgetLaw='https://www.khaochakan.go.th/_files/data/data_HmgqDBgp.pdf';
export function budgetTotals(b:Budget){const decrease=b.decreases.reduce((n,r)=>n+cents(r.amount),0),increase=b.increases.reduce((n,r)=>n+cents(r.amount),0);return {decrease,increase,difference:decrease-increase};}
export function budgetIssues(b:Budget){const issues:string[]=[];const result=budgetSchema.safeParse(b);if(!result.success)return result.error.issues.map(x=>x.message);const totals=budgetTotals(b);if(!totals.decrease||totals.difference!==0)issues.push('ยอดโอนลดและโอนเพิ่มต้องเท่ากันและมากกว่าศูนย์');const ids=new Set<string>();for(const [kind,rows] of [['โอนลด',b.decreases],['โอนเพิ่ม',b.increases]] as const)rows.forEach((r,i)=>{if(ids.has(r.id))issues.push('มีรหัสรายการซ้ำ');ids.add(r.id);if(!r.department||!r.plan||!r.work||!r.category||!r.type||!r.item)issues.push(`${kind}รายการ ${i+1}: ระบุหน่วยงาน แผนงาน งาน หมวด ประเภท และรายการให้ครบ`);if(cents(r.amount)<=0)issues.push(`${kind}รายการ ${i+1}: ระบุยอดโอนมากกว่าศูนย์`);if(kind==='โอนลด'&&cents(r.amount)>cents(r.remaining))issues.push(`โอนลดรายการ ${i+1}: เกินยอดคงเหลือที่ใช้ได้ก่อนโอน`);if(kind==='โอนเพิ่ม'&&(r.investment||r.fund.replace(/\s/g,'')==='งบลงทุน'))issues.push(...referenceIssues({...emptyReference(),...r}).map(message=>`โอนเพิ่มรายการ ${i+1}: ${message}`));if(kind==='โอนเพิ่ม'&&r.newItem&&(cents(r.allocated)!==0||cents(r.remaining)!==0))issues.push(`ตั้งจ่ายใหม่รายการ ${i+1}: งบเดิมและคงเหลือก่อนโอนต้องเป็นศูนย์`);});if(!b.authorityChecked||b.authority==='verify')issues.push('ยืนยันผู้มีอำนาจอนุมัติและข้อระเบียบก่อนสร้างบันทึก');if([...b.decreases,...b.increases].some(r=>(r.investment||r.fund.replace(/\s/g,'')==='งบลงทุน')&&(r.newItem||r.scopeChanged))&&b.authority!=='council')issues.push('เข้าข่ายข้อ 27: งบลงทุนที่เปลี่ยนลักษณะ ปริมาณ คุณภาพ หรือตั้งจ่ายใหม่ ต้องตรวจเสนอสภาท้องถิ่น');if(!b.organization||!b.recipient||!b.signer||!b.position||!b.reason)issues.push('ระบุหน่วยงาน ผู้รับ ผู้ลงนาม ตำแหน่ง และเหตุผลให้ครบ');return issues;}
export function newBudgetLine():BudgetLine{return {...emptyReference(),id:crypto.randomUUID(),department:'',plan:'',work:'',fund:'',category:'',type:'',item:'',allocated:'0.00',remaining:'0.00',amount:'0.00',newItem:false,investment:false,scopeChanged:false,purpose:'',specification:''};}
export function newBudget(date:string):Budget{return {title:'ขอโอนงบประมาณรายจ่าย',date,year:Number(date.slice(0,4))+543+(Number(date.slice(5,7))>=10?1:0),organization:'',department:'',phone:'',number:'',recipient:'นายกเทศมนตรี',signer:'',position:'',background:'ตามที่ได้ประกาศใช้เทศบัญญัติงบประมาณรายจ่ายประจำปีแล้วนั้น',reason:'',legalNotes:'',proposal:'',authority:'verify',authorityChecked:false,numeralStyle:'thai',decreases:[newBudgetLine()],increases:[newBudgetLine()],opinions:['ความเห็นหัวหน้าสำนักปลัด','ความเห็นผู้อำนวยการกองคลัง','ความเห็นปลัดเทศบาล','ความเห็นรองนายกเทศมนตรี','ความเห็นนายกเทศมนตรี'].map(title=>({title,name:'',position:title.replace('ความเห็น',''),comment:''}))};}
export function budgetSample(date:string){const b=newBudget(date);const base={...newBudgetLine(),department:'สำนักปลัดเทศบาล',plan:'บริหารงานทั่วไป',work:'บริหารทั่วไป'};b.organization='เทศบาลตำบลราไวย์';b.department='สำนักปลัดเทศบาล';b.title='ข้อมูลสาธิต — โอนงบประมาณเพื่อจัดหาระบบโทรศัพท์';b.reason='มีความจำเป็นในการปรับปรุงระบบโทรศัพท์และเครือข่าย เพื่อเพิ่มประสิทธิภาพการติดต่อราชการ (ข้อมูลสาธิตจากตัวอย่าง ไม่ใช่รายการอนุมัติจริง)';b.decreases=[{...base,id:crypto.randomUUID(),fund:'งบดำเนินงาน',category:'ค่าวัสดุ',type:'วัสดุโฆษณาและเผยแพร่',item:'วัสดุโฆษณาและเผยแพร่',allocated:'500000.00',remaining:'281000.00',amount:'152460.00'}];b.increases=[['อุปกรณ์ค้นหาเส้นทางเครือข่าย (Router)','21300.00'],['ตู้เก็บอุปกรณ์กระจายสัญญาณแบบติดผนัง','15600.00'],['Smart Cloud Managed PoE Switch','40200.00'],['อุปกรณ์แปลงและรับส่งสัญญาณผ่านสายใยแก้วนำแสง','4500.00'],['อุปกรณ์ระบบโทรศัพท์ IP-PBX','32100.00'],['เครื่องโทรศัพท์ IP Phone','38760.00']].map(([item,amount],i)=>({...base,id:crypto.randomUUID(),fund:'งบลงทุน',category:'ค่าครุภัณฑ์',type:item.includes('โทรศัพท์')?'ครุภัณฑ์สำนักงาน':'ครุภัณฑ์คอมพิวเตอร์หรืออิเล็กทรอนิกส์',item,amount,purpose:`เพื่อจ่ายเป็นค่าจัดซื้อ ${item} จำนวน ${[1,2,3,1,1,19][i]} ${i===1?'ตู้':'เครื่อง'} (ตัวอย่าง โปรดตรวจจำนวนและคุณลักษณะก่อนใช้จริง)`,newItem:true,investment:true}));b.authority='council';return b;}
