import 'server-only';
import {randomUUID} from 'node:crypto';
import {db,readDraft} from './db';
import {budgetSchema,budgetIssues,type BudgetRecord} from './budget';
import {budgetDraft} from './budget-document';
import {documentSchema} from './document';
function connection(){const c=db();c.exec('CREATE TABLE IF NOT EXISTS budget_transfers(id TEXT PRIMARY KEY,data TEXT NOT NULL,version INTEGER NOT NULL,updated_at TEXT NOT NULL,document_id TEXT,generated_version INTEGER)');return c;}
export function listBudgets():BudgetRecord[]{return connection().prepare('SELECT * FROM budget_transfers ORDER BY updated_at DESC').all().map(r=>({id:String(r.id),data:budgetSchema.parse(JSON.parse(String(r.data))),version:Number(r.version),updatedAt:String(r.updated_at),documentId:r.document_id?String(r.document_id):null}));}
export function saveBudgetRecord(input:unknown,id?:string,version?:number){const data=budgetSchema.parse(input),c=connection(),key=id||randomUUID(),now=new Date().toISOString();c.transaction(()=>{if(id){if(!c.prepare('UPDATE budget_transfers SET data=?,version=version+1,updated_at=? WHERE id=? AND version=?').run(JSON.stringify(data),now,id,version??-1).changes)throw new Error('รายการเปลี่ยนแล้ว กรุณาเปิดข้อมูลล่าสุด');}else c.prepare('INSERT INTO budget_transfers(id,data,version,updated_at) VALUES(?,?,1,?)').run(key,JSON.stringify(data),now);c.prepare('INSERT INTO audit(document_id,action,version,at) VALUES(?,?,?,?)').run(key,'budget_save',id?(version||0)+1:1,now);})();return listBudgets().find(r=>r.id===key)!;}
export function removeBudgetRecord(id:string,version:number){const c=connection();c.transaction(()=>{if(!c.prepare('DELETE FROM budget_transfers WHERE id=? AND version=?').run(id,version).changes)throw new Error('รายการเปลี่ยนแล้ว กรุณาเปิดข้อมูลล่าสุด');c.prepare('INSERT INTO audit(document_id,action,version,at) VALUES(?,?,?,?)').run(id,'budget_delete',version,new Date().toISOString());})();}
export function generateBudgetDocument(id:string,version:number){const c=connection();return c.transaction(()=>{const row=c.prepare('SELECT * FROM budget_transfers WHERE id=? AND version=?').get(id,version);if(!row)throw new Error('รายการเปลี่ยนแล้ว กรุณาบันทึกข้อมูลล่าสุด');if(row.document_id&&row.generated_version===version&&c.prepare('SELECT id FROM documents WHERE id=?').get(row.document_id))return readDraft(String(row.document_id));const b=budgetSchema.parse(JSON.parse(String(row.data))),issues=budgetIssues(b);if(issues.length)throw new Error(issues.join(' · '));const draft=documentSchema.parse(budgetDraft(b)),key=randomUUID(),now=new Date().toISOString();c.prepare('INSERT INTO documents(id,data,created_at,updated_at) VALUES(?,?,?,?)').run(key,JSON.stringify(draft),now,now);c.prepare('UPDATE budget_transfers SET document_id=?,generated_version=? WHERE id=?').run(key,version,id);c.prepare('INSERT INTO audit(document_id,action,version,at) VALUES(?,?,?,?)').run(key,'budget_document_create',1,now);return readDraft(key);})();}
