"use client";
import { PdfPreview } from "./pdf-preview";
import { useState } from "react";
import type { Draft } from "@/lib/document";
import { uploadAttachment } from "@/app/attachment-actions";
type Props={draft:Draft;onChange:(files:Draft['attachmentFiles'])=>void;onBusy:(busy:boolean)=>void;onPhrase:(phrase:Draft['attachmentPhrase'])=>void};
export function AttachmentEditor({draft,onChange,onBusy,onPhrase}:Props){
 const [busy,setBusy]=useState(false),[error,setError]=useState('');const files=draft.attachmentFiles;
 async function upload(file:File){setBusy(true);onBusy(true);setError('');try{if(files.length>=10)throw new Error('แนบได้ไม่เกิน 10 ไฟล์');const form=new FormData();form.set('file',file);const result=await uploadAttachment(form);if(!result.ok)throw new Error(result.error);if(files.reduce((n,a)=>n+a.bytes,0)+result.data.bytes>50*1024*1024)throw new Error('ไฟล์แนบรวมเกิน 50 MB');onChange([...files,result.data]);}catch(e){setError(e instanceof Error?e.message:'อัปโหลดไม่สำเร็จ');}finally{setBusy(false);onBusy(false);}}
 function move(index:number,offset:number){const next=[...files];[next[index],next[index+offset]]=[next[index+offset],next[index]];onChange(next);}
 return <details className="form-section" open><summary><strong>ไฟล์ที่ส่งไปพร้อมหนังสือ</strong><span>{files.length} ไฟล์</span></summary><div className="field-grid">
 <label className="wide">{busy?'กำลังจัดเก็บไฟล์…':'เพิ่ม PDF หรือรูปภาพ'}<input type="file" accept="application/pdf,image/png,image/jpeg" disabled={busy||files.length>=10} onChange={e=>{const f=e.currentTarget.files?.[0];e.currentTarget.value='';if(f)void upload(f);}}/></label>
 <p className="field-note wide">ไม่เกิน 10 MB ต่อไฟล์ รวม 50 MB · Word/Excel กรุณาแปลงเป็น PDF · รูปภาพจัดลง A4 ส่วน PDF คงขนาดหน้าเดิม ไฟล์แนบใช้สำหรับอ่าน/พิมพ์ PDF รวมไม่เก็บช่องกรอกหรือการตรวจลายเซ็นดิจิทัล โปรดใช้ต้นฉบับสำหรับตรวจลายเซ็น</p>
 {error&&<p className="wide overflow-alert" role="alert">{error}</p>}
 {files.map((a,index)=><div className="wide attachment-card" key={a.id}><label>รายการที่ {index+1}<input disabled={busy} value={a.description} maxLength={300} onChange={e=>onChange(files.map(x=>x.id===a.id?{...x,description:e.target.value}:x))}/></label><div className="attachment-controls"><label>จำนวน<input disabled={busy} type="number" min={1} max={999} value={a.quantity} onChange={e=>onChange(files.map(x=>x.id===a.id?{...x,quantity:Number(e.target.value)}:x))}/></label><label>หน่วย<select disabled={busy} value={a.unit} onChange={e=>onChange(files.map(x=>x.id===a.id?{...x,unit:e.target.value as typeof a.unit}:x))}>{['ฉบับ','ชุด','แผ่น'].map(unit=><option key={unit}>{unit}</option>)}</select></label><button type="button" title="เลื่อนขึ้น" disabled={busy||index===0} onClick={()=>move(index,-1)}>↑</button><button type="button" title="เลื่อนลง" disabled={busy||index===files.length-1} onClick={()=>move(index,1)}>↓</button><button type="button" disabled={busy} onClick={()=>onChange(files.filter(x=>x.id!==a.id))}>เอาออกจากร่าง</button></div><small>{a.name} · {a.originalAvailable&&<a href={`/api/attachments/${a.id}?original=1`}>ดาวน์โหลดต้นฉบับ</a>} · {a.pages} หน้า · {(a.bytes/1024/1024).toFixed(2)} MB</small></div>)}
 {!!files.length&&['internal','memorandum'].includes(draft.type)&&<label className="wide">ข้อความอ้างเอกสารแนบในเนื้อหา<select value={draft.attachmentPhrase} onChange={e=>onPhrase(e.target.value as Draft['attachmentPhrase'])}>{['ตามเอกสารที่แนบมาพร้อมนี้','รายละเอียดตามเอกสารแนบ','พร้อมนี้ได้แนบเอกสารประกอบการพิจารณา'].map(s=><option key={s}>{s}</option>)}</select></label>}
 <p className="field-note wide">{draft.type==='external'?'ระบบสร้าง “สิ่งที่ส่งมาด้วย” จากไฟล์ที่แนบเท่านั้น':'หนังสือภายในอ้างเอกสารในเนื้อความ ไม่เพิ่มหัวข้อ “สิ่งที่ส่งมาด้วย” ในส่วนหัว'}{draft.attachments&&!files.length?' · ร่างเดิมมีข้อความรายการแนบ แต่ยังไม่มีไฟล์ กรุณาแนบไฟล์เพื่อให้รายการปรากฏ':''}</p>
 </div></details>;
}
export function AttachmentPreview({files}:{files:Draft['attachmentFiles']}){if(!files.length)return null;return <div className="attachment-preview"><h3>เอกสารแนบตามลำดับส่ง</h3><p>{files.length} ไฟล์ · {files.reduce((n,a)=>n+a.pages,0)} หน้า · ส่งออก PDF จะรวมต่อท้ายหนังสือปะหน้า</p>{files.map((a,i)=><section key={a.id}><h4>{i+1}. {a.description} <a href={`/api/attachments/${a.id}`} target="_blank" rel="noreferrer">เปิดเต็มจอ</a></h4><PdfPreview title={`เอกสารแนบ ${i+1} ${a.description}`} url={`/api/attachments/${a.id}`}/></section>)}</div>;}
