"use client";
import {useEffect,useState} from 'react';
import {searchBudgetReferences} from '@/app/budget-reference-actions';
import {referenceSources,circulars,referenceText,type ReferenceSource,type ReferenceSearch,type CatalogItem} from '@/lib/budget-references';
import type {BudgetLine} from '@/lib/budget';
import s from './budget-transfers.module.css';
export type OpenReference=(source:ReferenceSource,page:number)=>void;
export function BudgetReferencePicker({value:r,onChange,onOpen}:{value:BudgetLine;onChange:(value:BudgetLine)=>void;onOpen:OpenReference}){
 const [searchOpen,setSearchOpen]=useState(false);
 const [query,setQuery]=useState(''),[source,setSource]=useState(''),[results,setResults]=useState<ReferenceSearch>({items:[],pages:[]}),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 const [selected,setSelected]=useState<CatalogItem|null>(null);
 useEffect(()=>{if(!searchOpen)return;let active=true;setLoading(true);const timer=setTimeout(()=>{searchBudgetReferences(query,source).then(x=>{if(active){setResults(x);setError('');}}).catch(()=>{if(active)setError('ค้นหาไม่สำเร็จ ลองใหม่ได้โดยเปลี่ยนคำค้น');}).finally(()=>{if(active)setLoading(false);});},250);return()=>{active=false;clearTimeout(timer);};},[query,source,searchOpen]);
 function patch(p:Partial<BudgetLine>){onChange({...r,...p,referenceChecked:false});}
 function choose(item:CatalogItem){setSelected(item);patch({catalogId:item.id,sourceId:item.source as BudgetLine['sourceId'],sourcePage:item.page,sourceItem:`${item.code} ${item.title}`,pricingBasis:'standard',citedCirculars:['1095'],classificationPage:item.classificationPage,...(item.type?{type:item.type,category:'ค่าครุภัณฑ์',fund:'งบลงทุน',investment:true}:{})});onOpen(item.source,item.page);}
 return <div className={s.referencePicker}><h3>หมวดครุภัณฑ์และแหล่งอ้างอิงรายรายการ</h3><details onToggle={e=>setSearchOpen(e.currentTarget.open)}><summary>ค้นอุปกรณ์ / เปิดบัญชีและหนังสือจำแนกประเภท</summary><label>ค้นชื่ออุปกรณ์หรือคำในเอกสาร<input value={query} maxLength={150} placeholder="เช่น Router, ตู้เหล็ก, เครื่องพิมพ์" onChange={e=>setQuery(e.target.value)}/></label><label>ค้นในเอกสาร<select value={source} onChange={e=>setSource(e.target.value)}><option value="">ทุกฉบับ</option>{Object.entries(referenceSources).map(([id,v])=><option key={id} value={id}>{v.short}</option>)}</select></label>
 <p className={s.note}>เทียบคุณลักษณะก่อนเลือก ชื่อเหมือนกันอาจไม่ใช่รายการเดียวกัน · ราคาที่แสดงเป็นราคาอ้างอิง ไม่เปลี่ยนยอดโอนให้</p>
 <p className={s.note}>คอมพิวเตอร์ 1–11 ใช้ฉบับ พ.ค. 2569; 12–70 ใช้ ธ.ค. 2568 · ว 1095 เป็นไฟล์สแกน ค้นได้เฉพาะหัวข้อที่ทำดัชนีไว้</p>
 {loading?<p role="status">กำลังค้น…</p>:error?<p role="alert">{error}</p>:<div className={s.results}>{results.items.map(item=><article key={item.id}><strong>{item.code}. {item.title}</strong><small>{referenceSources[item.source].short} · หน้า PDF {item.page} · ราคาในบัญชี {Number(item.price).toLocaleString()} บาท</small><div><button type="button" onClick={()=>choose(item)}>ใช้อ้างอิงรายการนี้</button> <button type="button" onClick={()=>onOpen(item.source,item.page)}>ดูต้นฉบับ</button>{item.specPage&&<button type="button" onClick={()=>onOpen(item.source,item.specPage!)}>ดูคุณลักษณะ</button>}</div></article>)}{results.pages.map(p=><button type="button" key={`${p.source}-${p.page}`} onClick={()=>onOpen(p.source,p.page)}>{referenceSources[p.source].short} · หน้า PDF {p.page} — เปิดหน้าที่พบคำค้น</button>)}{!results.items.length&&!results.pages.length&&<p>ไม่พบในดัชนีนี้ ไม่ได้หมายความว่าไม่มีในบัญชีทั้งหมด เปิดต้นฉบับตรวจเพิ่มเติมได้</p>}</div>}
 <div className={s.sourceButtons}>{Object.entries(referenceSources).map(([id,v])=><button type="button" key={id} onClick={()=>onOpen(id as ReferenceSource,1)}>{v.short}</button>)}</div></details>
 {selected&&<div className={s.note}>เลือกอ้างอิง: {selected.title} {selected.type?'ระบบแนะนำประเภทจาก ว 1095 โปรดตรวจหน้าต้นฉบับอีกครั้ง':'รายการบริการ/ซอฟต์แวร์ ต้องพิจารณางบและประเภทแยกตามลักษณะการจัดหา'}{selected.specification&&<button type="button" onClick={()=>{if(r.specification&&!confirm('แทนคุณลักษณะที่กรอกด้วยข้อความจากบัญชีที่เลือกหรือไม่?'))return;patch({specification:selected.specification});}}>นำคุณลักษณะจากบัญชีมาใส่</button>}</div>}
 <label>ฐานการอ้างอิงราคา<select value={r.pricingBasis} onChange={e=>patch({pricingBasis:e.target.value as BudgetLine['pricingBasis']})}><option value="unverified">รอเทียบกับบัญชี</option><option value="standard">ตรงตามบัญชีมาตรฐาน / เกณฑ์คอมพิวเตอร์</option><option value="local">นอกบัญชี / คุณลักษณะแตกต่าง — ราคาท้องถิ่น</option></select></label>
 {r.pricingBasis==='standard'&&<><label>ฉบับที่อ้าง<select value={r.sourceId} onChange={e=>patch({sourceId:e.target.value as BudgetLine['sourceId'],catalogId:'',sourceItem:'',sourcePage:1})}><option value="">เลือกฉบับ</option>{Object.entries(referenceSources).filter(([id])=>id!=='classification').map(([id,v])=><option key={id} value={id}>{v.short}</option>)}</select></label><label>เลขรายการและชื่อรายการในบัญชี<input value={r.sourceItem} onChange={e=>patch({sourceItem:e.target.value,catalogId:''})}/></label><label>หน้า PDF ที่อ้าง (นับจากปก)<input type="number" min={1} max={118} value={r.sourcePage} onChange={e=>patch({sourcePage:Number(e.target.value),catalogId:''})}/></label>{r.sourceId&&<button type="button" onClick={()=>onOpen(r.sourceId as ReferenceSource,r.sourcePage)}>เปิดหน้าอ้างอิง</button>}</>}
 {r.pricingBasis==='local'&&<><label>เหตุผลที่ไม่ใช้รายการมาตรฐาน<textarea value={r.pricingReason} onChange={e=>patch({pricingReason:e.target.value})} placeholder="ระบุรายการที่เทียบแล้ว และคุณลักษณะจำเป็นที่แตกต่าง หรือไม่พบรายการใด"/></label><label>หลักฐานสืบราคา / เลขใบเสนอราคา / แหล่งราคาและวันที่<textarea value={r.pricingEvidence} onChange={e=>patch({pricingEvidence:e.target.value})} placeholder="ระบุหลักฐานจริง และแนบเอกสารประกอบในหน้าร่างหนังสือ"/></label><button type="button" onClick={()=>patch({citedCirculars:['1095','1989','7509']})}>เลือกชุดหนังสืออ้างอิงตามตัวอย่าง</button><p className={s.note}>ว 1095 ใช้จำแนกประเภท · ว 1989 เกี่ยวกับการตั้งงบจัดซื้อ · ว 7509 เกี่ยวกับแผนพัฒนาท้องถิ่น เลือกเฉพาะฉบับที่ตรวจว่าใช้กับกรณีนี้</p></>}
 <p>หนังสือสั่งการประกอบ</p>{Object.entries(circulars).map(([code,title])=><label className={s.check} key={code}><input type="checkbox" checked={r.citedCirculars.includes(code as keyof typeof circulars)} onChange={e=>patch({citedCirculars:e.target.checked?[...r.citedCirculars,code as keyof typeof circulars]:r.citedCirculars.filter(x=>x!==code)})}/>{title}</label>)}
 <div className={s.sourceButtons}><button type="button" onClick={()=>onOpen('classification',42)}>ว 1095 · สำนักงาน / โทรศัพท์</button><button type="button" onClick={()=>onOpen('classification',52)}>ว 1095 · คอมพิวเตอร์</button></div>
 <details><summary>ข้อความที่จะพิมพ์ใต้รายการ</summary>{referenceText(r).map((t,i)=><p key={i}>{t}</p>)}</details>
 <label className={s.check}><input type="checkbox" checked={r.referenceChecked} onChange={e=>onChange({...r,referenceChecked:e.target.checked})}/>ตรวจประเภท คุณลักษณะ ฉบับอ้างอิง และความเกี่ยวข้องของหนังสือที่เลือกแล้ว</label></div>;
}
