"use client";
import {BudgetReferencePicker,type OpenReference} from './budget-reference-picker';
import {PdfPreview} from './pdf-preview';
import {referenceSources,type ReferenceSource} from '@/lib/budget-references';

import {useEffect,useMemo,useRef,useState,useTransition} from 'react';
import {Plus,ArrowLeft,ArrowRight,Wallet,Save,FileText,Trash2} from 'lucide-react';
import {budgetTotals,budgetIssues,baht,cents,newBudget,newBudgetLine,budgetSample,budgetLaw,type Budget,type BudgetLine,type BudgetRecord} from '@/lib/budget';
import {budgetDraft} from '@/lib/budget-document';
import {today,type SavedDraft} from '@/lib/document';
import {documentHtml,type DocumentAssets} from '@/lib/render-document';
import {getBudgets,saveBudget,deleteBudget,createBudgetMemo} from '@/app/budget-actions';
import s from './budget-transfers.module.css';
export function BudgetTransfers({assets,onOpenDocument,onDirtyChange}:{assets:DocumentAssets;onOpenDocument:(d:SavedDraft)=>void;onDirtyChange:(dirty:boolean)=>void}){
 const [items,setItems]=useState<BudgetRecord[]>([]),[form,setForm]=useState<Budget|null>(null),[record,setRecord]=useState<BudgetRecord|null>(null),[baseline,setBaseline]=useState(''),[message,setMessage]=useState(''),[query,setQuery]=useState(''),[year,setYear]=useState(''),[busy,start]=useTransition();
 const [reference,setReference]=useState<{source:ReferenceSource;page:number}|null>(null);
 const openReference:OpenReference=(source,page)=>setReference({source,page:Math.max(1,Math.min(referenceSources[source].pages,page||1))});
 const dirty=!!form&&(!record||JSON.stringify(form)!==baseline);
 useEffect(()=>{onDirtyChange(dirty);return()=>onDirtyChange(false);},[dirty,onDirtyChange]);
 useEffect(()=>{getBudgets().then(setItems).catch(()=>setMessage('โหลดรายการไม่ได้ กรุณาลองใหม่'));},[]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 function leave(){return !dirty||confirm('มีข้อมูลโอนงบที่ยังไม่บันทึก ต้องการละทิ้งการแก้ไขหรือไม่?');}
 function edit(data:Budget,r:BudgetRecord|null){if(!leave())return;setRecord(r);setForm(data);setBaseline(JSON.stringify(data));setMessage('');}
 function set<K extends keyof Budget>(k:K,v:Budget[K]){setForm(f=>f?{...f,[k]:v,...(['decreases','increases','authority'].includes(k)?{authorityChecked:false}:{})}:f);}
 function run(fn:()=>Promise<void>){start(async()=>{try{await fn();}catch(e){setMessage(e instanceof Error?e.message:'ดำเนินการไม่สำเร็จ');}});}
 async function persist(){const result=await saveBudget(form,record?.id,record?.version);if(!result.ok)throw new Error(result.error);setRecord(result.data);setForm(result.data.data);setBaseline(JSON.stringify(result.data.data));setItems(await getBudgets());return result.data;}
 const normalized=(v:string)=>v.replace(/[๐-๙]/g,c=>String('๐๑๒๓๔๕๖๗๘๙'.indexOf(c))).toLowerCase();
 const shown=items.filter(r=>(!year||String(r.data.year)===year)&&normalized(JSON.stringify(r.data)).includes(normalized(query)));
 const total=form?budgetTotals(form):null,issues=form?budgetIssues(form):[];
 function field<K extends keyof Budget>(key:K,label:string,multiline=false){if(!form)return null;return <label>{label}{multiline?<textarea rows={3} value={String(form[key])} onChange={e=>set(key,e.target.value as Budget[K])}/>:<input value={String(form[key])} type={key==='date'?'date':key==='year'?'number':'text'} onChange={e=>set(key,(key==='year'?Number(e.target.value):e.target.value) as Budget[K])}/>}</label>;}
 return <main className={`page-main ${s.root}`}><header className={s.header}><div><span>งานธุรการ · การเงินและงบประมาณ</span><h1><Wallet size={26}/> โอนงบประมาณ</h1><p>โอนลด → โอนเพิ่ม / ตั้งจ่ายใหม่ → จัดทำบันทึกข้อความ</p></div><button className="primary" disabled={busy} onClick={()=>edit(newBudget(today()),null)}><Plus size={18}/>เพิ่มคำขอโอนงบ</button></header>
 {message&&<div className={s.message} role="status">{message}</div>}
 {!form?<><div className={s.search}><input aria-label="ค้นหางานโอนงบ" placeholder="ค้นหาเรื่อง รายการ แผนงาน หรือหน่วยงาน" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="ปีงบประมาณ" value={year} onChange={e=>setYear(e.target.value)}><option value="">ทุกปีงบประมาณ</option>{[...new Set(items.map(r=>r.data.year))].sort((a,b)=>b-a).map(y=><option key={y}>{y}</option>)}</select><button onClick={()=>run(async()=>setItems(await getBudgets()))}>รีเฟรช</button></div><div className={s.cards}><div><strong>{shown.length}</strong>คำขอโอนงบ</div><div><strong>{baht(shown.reduce((n,r)=>n+budgetTotals(r.data).decrease,0))}</strong>บาท · วงเงินตามคำขอ</div><div><strong>{shown.filter(r=>r.documentId).length}</strong>รายการที่สร้างบันทึกแล้ว</div></div><p className={s.note}>เป็นทะเบียนคำขอ ไม่ใช่ยอดเบิกจ่ายหรือการอนุมัติในระบบบัญชีของเทศบาล</p><div className={s.table}><table><thead><tr><th>เรื่อง / หน่วยงาน</th><th>ปี</th><th>โอนลด</th><th>โอนเพิ่ม</th><th>เอกสาร</th><th/></tr></thead><tbody>{shown.map(r=><tr key={r.id}><td><button className="text-button" onClick={()=>edit(r.data,r)}>{r.data.title}</button><small>{r.data.department} · {r.data.date}</small></td><td>{r.data.year}</td><td>{baht(budgetTotals(r.data).decrease)}</td><td>{baht(budgetTotals(r.data).increase)}</td><td>{r.documentId?'มีร่างบันทึก':'ยังไม่สร้าง'}</td><td><button aria-label={`ลบคำขอ ${r.data.title}`} disabled={busy} onClick={()=>{if(confirm('ลบคำขอนี้? บันทึกข้อความที่สร้างไว้จะยังคงอยู่'))run(async()=>{await deleteBudget(r.id,r.version);setItems(await getBudgets());});}}><Trash2 size={16}/></button></td></tr>)}</tbody></table>{!shown.length&&<p>ยังไม่มีคำขอ เริ่มจาก “เพิ่มคำขอโอนงบ” หรือทดลองรูปแบบจากตัวอย่าง</p>}</div><button className="secondary" onClick={()=>edit(budgetSample(today()),null)}>ลองแพตเทิร์นจากไฟล์ตัวอย่าง</button></>:
 <><div className={s.toolbar}><button disabled={busy} onClick={()=>{if(leave())setForm(null);}}><ArrowLeft size={16}/>กลับทะเบียน</button><button disabled={busy} onClick={()=>run(async()=>{await persist();setMessage('บันทึกคำขอโอนงบแล้ว');})}><Save size={16}/>บันทึกคำขอ</button><button className="primary" disabled={busy||issues.length>0} onClick={()=>run(async()=>{const r=dirty||!record?await persist():record;const d=await createBudgetMemo(r.id,r.version);onOpenDocument(d);})}><FileText size={16}/>สร้าง / เปิดบันทึกข้อความ<ArrowRight size={16}/></button></div>
 <div className={s.cards}><div>โอนลด<strong>{baht(total!.decrease)}</strong>บาท</div><div>โอนเพิ่ม<strong>{baht(total!.increase)}</strong>บาท</div><div className={total!.difference?s.invalid:s.balanced}>ผลต่าง<strong>{baht(total!.difference)}</strong>{total!.difference?'ยอดยังไม่สมดุล':'ยอดตรงกัน'}</div></div>
 <div className={s.layout}><fieldset disabled={busy} className={s.form}><section><h2>1. ข้อมูลหนังสือ</h2><div className={s.grid}>{field('title','เรื่อง')}{field('year','ปีงบประมาณ พ.ศ.')}{field('date','วันที่')}{field('number','เลขที่หนังสือ')}{field('organization','หน่วยงานเทศบาล')}{field('department','ส่วนราชการเจ้าของเรื่อง')}{field('phone','โทรศัพท์')}{field('recipient','เรียน')}{field('signer','ผู้เสนอ / ผู้ลงนาม')}{field('position','ตำแหน่ง')}<label>ตัวเลขในเอกสาร<select value={form.numeralStyle} onChange={e=>set('numeralStyle',e.target.value as Budget['numeralStyle'])}><option value="thai">เลขไทย</option><option value="arabic">เลขอารบิก</option></select></label></div>{field('background','เรื่องเดิม',true)}{field('reason','ข้อเท็จจริง / เหตุผลความจำเป็น',true)}</section>
 {(['decreases','increases'] as const).map(key=><section key={key}><h2>{key==='decreases'?'2. รายการโอนลด':'3. รายการโอนเพิ่ม / ตั้งจ่ายใหม่'}</h2>{form[key].map((line,i)=><BudgetLineForm key={line.id} value={line} index={i} onOpenReference={openReference} decrease={key==='decreases'} onChange={value=>set(key,form[key].map(r=>r.id===line.id?value:r))} onRemove={form[key].length>1?()=>set(key,form[key].filter(r=>r.id!==line.id)):undefined}/>)}<button type="button" disabled={form[key].length>=20} onClick={()=>{const first=form[key][0];set(key,[...form[key],{...newBudgetLine(),department:first.department||form.department,plan:first.plan,work:first.work}]);}}><Plus size={16}/>เพิ่มรายการ {key==='decreases'?'โอนลด':'โอนเพิ่ม'}</button></section>)}
 <section><h2>4. ระเบียบและเส้นทางเสนอ</h2><p className={s.note}>ข้อ 26: ผู้บริหารท้องถิ่น · ข้อ 27: งบลงทุนที่เปลี่ยนลักษณะ ปริมาณ คุณภาพ หรือตั้งจ่ายใหม่ เป็นอำนาจสภาท้องถิ่น <a href={budgetLaw} target="_blank" rel="noreferrer">เปิดระเบียบ</a></p><label>ผู้มีอำนาจอนุมัติ<select value={form.authority} onChange={e=>set('authority',e.target.value as Budget['authority'])}><option value="verify">รอตรวจสอบ</option><option value="executive">ผู้บริหารท้องถิ่น — ข้อ 26</option><option value="council">สภาท้องถิ่น — ข้อ 27</option></select></label>{field('legalNotes','ระเบียบ / หนังสือสั่งการเพิ่มเติม',true)}{field('proposal','ข้อพิจารณา / ข้อเสนอแนะ (เว้นว่างเพื่อใช้ข้อความตามเส้นทางเสนอ)',true)}<label className={s.check}><input type="checkbox" checked={form.authorityChecked} onChange={e=>set('authorityChecked',e.target.checked)}/>ตรวจผู้มีอำนาจและข้อระเบียบที่ใช้กับรายการนี้แล้ว</label></section>
 <section><h2>5. ความเห็นผู้เกี่ยวข้อง</h2>{form.opinions.map((p,i)=><details key={i}><summary>{p.title||`ความเห็น ${i+1}`}</summary><div className={s.grid}>{(['title','name','position','comment'] as const).map((k,j)=><label key={k}>{['หัวข้อความเห็น','ชื่อ','ตำแหน่ง','ข้อความความเห็น (เว้นว่างเป็นเส้นประ)'][j]}<input value={p[k]} onChange={e=>set('opinions',form.opinions.map((x,n)=>n===i?{...x,[k]:e.target.value}:x))}/></label>)}</div></details>)}</section>
 <section><h2>ตรวจความครบถ้วน</h2>{issues.length?<ul className={s.invalid}>{issues.map((issue,i)=><li key={i}>{issue}</li>)}</ul>:<p className={s.balanced}>ยอดสมดุลและข้อมูลพร้อมสร้างบันทึกฉบับร่าง</p>}<p className={s.note}>คงเหลือก่อนโอนต้องเป็นยอดที่โอนได้จริงหลังตรวจภาระผูกพันกับกองคลัง ระบบไม่ได้ดึงยอดบัญชีอัตโนมัติ การสร้างร่างไม่ใช่การอนุมัติ</p></section></fieldset><aside className={s.preview}>{reference?<><h2>อ่านระเบียบควบคู่</h2><p>{referenceSources[reference.source].short}</p><button type="button" onClick={()=>setReference(null)}>กลับตัวอย่างบันทึก</button> <a href={`/api/budget-references/${reference.source}#page=${reference.page}`} target="_blank" rel="noreferrer">เปิดทั้งเล่ม</a><label>หน้า PDF<input type="number" min={1} max={referenceSources[reference.source].pages} value={reference.page} onChange={e=>openReference(reference.source,Number(e.target.value))}/></label><div className={s.previewScroll}><PdfPreview url={`/api/budget-references/${reference.source}`} title={referenceSources[reference.source].title} pageNumber={reference.page}/></div></>:<BudgetPreview value={form} assets={assets}/>}</aside></div></>}
 </main>;
}
function BudgetLineForm({value:r,index,decrease,onChange:notify,onRemove,onOpenReference}:{onOpenReference:OpenReference;value:BudgetLine;index:number;decrease:boolean;onChange:(r:BudgetLine)=>void;onRemove?:()=>void}){
 const onChange=(value:BudgetLine)=>notify({...value,referenceChecked:false});
 const field=(k:keyof BudgetLine,label:string,cash=false)=><label>{label}<input value={String(r[k])} inputMode={cash?'decimal':undefined} onChange={e=>onChange({...r,[k]:cash?e.target.value.replace(/[๐-๙]/g,c=>String('๐๑๒๓๔๕๖๗๘๙'.indexOf(c))).replaceAll(',',''):e.target.value})}/></label>;
 return <details className={s.line} open={index===0}><summary>{index+1}. {r.item||'รายการใหม่'} — {baht(cents(r.amount))} บาท</summary><div className={s.grid}>{field('department','หน่วยงาน')}{field('plan','แผนงาน')}{field('work','งาน')}{field('fund','งบรายจ่าย')}{field('category','หมวด')}{field('type','ประเภท')}{field('item','รายการ')}{field('allocated','งบตั้งไว้เดิม (บาท)',true)}{field('remaining','คงเหลือใช้ได้ก่อนโอน (บาท)',true)}{field('amount',decrease?'โอนลดครั้งนี้ (บาท)':'โอนเพิ่มครั้งนี้ (บาท)',true)}</div><p className={s.balance}>คงเหลือหลังโอน <strong>{baht(cents(r.remaining)+(decrease?-1:1)*cents(r.amount))} บาท</strong></p>{!decrease&&<label className={s.check}><input type="checkbox" checked={r.newItem} onChange={e=>onChange({...r,newItem:e.target.checked})}/>ตั้งจ่ายเป็นรายการใหม่</label>}<label className={s.check}><input type="checkbox" checked={r.investment} onChange={e=>onChange({...r,investment:e.target.checked})}/>เป็นงบลงทุน</label><label className={s.check}><input type="checkbox" checked={r.scopeChanged} onChange={e=>onChange({...r,scopeChanged:e.target.checked})}/>มีการเปลี่ยนลักษณะ ปริมาณ หรือคุณภาพ</label>{!decrease&&<><BudgetReferencePicker value={r} onChange={notify} onOpen={onOpenReference}/><label>เพื่อจ่ายเป็น / จำนวนหน่วย<textarea rows={2} value={r.purpose} onChange={e=>onChange({...r,purpose:e.target.value})}/></label><label>คุณลักษณะและแหล่งอ้างอิง<textarea rows={4} value={r.specification} onChange={e=>onChange({...r,specification:e.target.value})}/></label></>}{onRemove&&<button type="button" onClick={onRemove}>เอารายการออก</button>}</details>;
}
function BudgetPreview({value,assets}:{value:Budget;assets:DocumentAssets}){
 const [draft,setDraft]=useState(value),[height,setHeight]=useState(1123),[warning,setWarning]=useState('');const ref=useRef<HTMLIFrameElement>(null);
 useEffect(()=>{const timer=setTimeout(()=>setDraft(value),300);return()=>clearTimeout(timer);},[value]);
 const html=useMemo(()=>documentHtml(budgetDraft(draft),assets),[draft,assets]);
 useEffect(()=>{const listener=(e:MessageEvent)=>{if(e.source!==ref.current?.contentWindow||e.data?.source!=='sarabun-preview')return;if(Number.isFinite(e.data.height))setHeight(e.data.height);setWarning(e.data.overflow||e.data.error?'มีองค์ประกอบยาวเกินหน้า กรุณาแบ่งรายละเอียด':'');};window.addEventListener('message',listener);return()=>window.removeEventListener('message',listener);},[]);
 return <div><h2>ตัวอย่างบันทึกข้อความ</h2><p>ฉบับร่าง · A4 · เปิดในหน้าจัดทำหนังสือเพื่อแนบไฟล์และส่งออก PDF</p>{warning&&<p role="alert">{warning}</p>}<div className={s.previewScroll}><div style={{width:516,height:height*.65}}><iframe ref={ref} title="ตัวอย่างบันทึกโอนงบประมาณ" srcDoc={html} sandbox="allow-scripts" style={{width:794,height,transform:'scale(.65)',transformOrigin:'top left',border:0}}/></div></div></div>;
}
