"use client";
import { useEffect,useRef,useState,useTransition } from "react";
import { BookOpen,Plus,Cloud,Search,X } from "lucide-react";
import { listLegalReferences,saveLegalReference,uploadLegalReference } from "@/app/legal-actions";
import { lawCategories,lawStatuses,type LegalRecord } from "@/lib/legal";
import s from "./law-library.module.css";
export function LawLibrary({connected}:{connected:boolean}){
 const [items,setItems]=useState<LegalRecord[]>([]),[query,setQuery]=useState(""),[category,setCategory]=useState("all"),[status,setStatus]=useState("all"),[editing,setEditing]=useState<LegalRecord|null>(null),[formOpen,setFormOpen]=useState(false),[compare,setCompare]=useState<string[]>([]),[message,setMessage]=useState(""),[pending,start]=useTransition();
 const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{listLegalReferences().then(setItems).catch(()=>setMessage("โหลดคลังไม่สำเร็จ กรุณาลองโหลดใหม่"));},[]);
 useEffect(()=>{if(formOpen)dialog.current?.showModal();},[formOpen]);
 const norm=(v:string)=>v.toLowerCase().replace(/[๐-๙]/g,c=>String("๐๑๒๓๔๕๖๗๘๙".indexOf(c)));
 const filtered=items.filter(x=>(category==="all"||category===x.category)&&(status==="all"||status===x.status)&&norm([x.title,x.section,x.category,x.tags,x.notes,x.highlight,x.year].join(" ")).includes(norm(query)));
 const categories=Array.from(new Set([...lawCategories,...items.map(x=>x.category)]));
 function run(job:()=>Promise<void>){start(async()=>{try{await job();}catch(e){setMessage(e instanceof Error?e.message:"ดำเนินการไม่สำเร็จ");}});}
 function edit(x:LegalRecord|null){setEditing(x);setMessage("");setFormOpen(true);}
 function close(){if(!pending&&confirm("ปิดฟอร์มโดยไม่บันทึกหรือไม่?"))setFormOpen(false);}
 function source(x:LegalRecord){return x.fileName?`/api/legal/${x.id}?inline=1#page=${x.page}`:x.url;}
 return <main className={`page-main ${s.root}`}><header className={s.header}><div><span>KNOWLEDGE LIBRARY</span><h1>คลังกฎหมายและระเบียบ</h1><p>เก็บฉบับที่ใช้ ค้นประเด็นที่จำ และเปิดอ่านเมื่อต้องการ</p></div><button className="primary" onClick={()=>edit(null)}><Plus size={18}/>เพิ่มเอกสาร</button></header>
 <div className={s.stats}><div><BookOpen/><strong>{items.length}</strong>เอกสารในคลัง</div><div><strong>{new Set(items.map(x=>x.category)).size}</strong>หมวดหมู่ที่ใช้</div><div><Cloud size={18}/>{connected?"พร้อมอัปโหลด Drive":"บันทึกในเครื่องได้ • Drive ยังไม่เชื่อมต่อ"}</div></div>
 {message&&<p className={s.message} role="status">{message}</p>}
 <section className={s.panel}><div className={s.filters}><Search size={19}/><input aria-label="ค้นคลังกฎหมาย" placeholder="ชื่อกฎหมาย มาตรา แท็ก ปี หรือประเด็นที่จดไว้" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="หมวดหมู่" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">ทุกหมวดหมู่</option>{categories.map(c=><option key={c}>{c}</option>)}</select><select aria-label="สถานะกฎหมาย" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">ทุกสถานะ</option>{Object.entries(lawStatuses).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><button disabled={pending} onClick={()=>run(async()=>setItems(await listLegalReferences()))}>โหลดใหม่</button></div>
 <div className={s.cards}>{filtered.map(x=><article className={s.card} key={x.id}><div className={s.meta}>{x.category} · {x.year?`พ.ศ. ${x.year}`:"ไม่ระบุปี"}</div><h2>{x.title}</h2><span className={s.status}>{lawStatuses[x.status]}</span><p>{x.section}</p>{x.highlight&&<mark className={s.highlight}>หน้า {x.page} · {x.highlight}</mark>}<p className={s.notes}>{x.notes}</p>{x.tags&&<small className={s.tags}>#{x.tags.split(/[,，]/).map(v=>v.trim()).filter(Boolean).join(" #")}</small>}<div className={s.actions}><button onClick={()=>setCompare([x.id])}>อ่าน / ดูโน้ต</button><button onClick={()=>setCompare(c=>c.includes(x.id)?c.filter(id=>id!==x.id):c.length<2?[...c,x.id]:[c[0],x.id])}>{compare.includes(x.id)?"✓ เลือกเทียบแล้ว":"เลือกเทียบ"}</button><button onClick={()=>edit(x)}>แก้ไข</button></div><div className={s.actions}>{x.fileName&&<a href={`/api/legal/${x.id}`} target="_blank" rel="noreferrer">ดาวน์โหลด PDF</a>}{x.driveFileId&&<a href={`https://drive.google.com/file/d/${encodeURIComponent(x.driveFileId)}/view`} target="_blank" rel="noreferrer">เปิดไฟล์ Drive ↗</a>}<button disabled={pending||!x.fileName||!connected} onClick={()=>run(async()=>{await uploadLegalReference(x.id);setItems(await listLegalReferences());setMessage("อัปโหลด PDF ไปยังโฟลเดอร์หมวดหมู่บน Drive แล้ว");})}><Cloud size={15}/>อัปโหลด Drive</button></div></article>)}</div>{!filtered.length&&<div className={s.empty}><BookOpen size={36}/><h2>{items.length?"ไม่พบเอกสารตามตัวกรอง":"เริ่มคลังความรู้ของหน่วยงาน"}</h2><p>เพิ่ม PDF ลิงก์ต้นฉบับ หรือบันทึกอ้างอิง แล้วจัดหมวดหมู่ไว้ค้นภายหลัง</p></div>}</section>
 {compare.length>0&&<section className={s.panel}><div className={s.readerHeader}><h2>{compare.length===2?"อ่านเปรียบเทียบ 2 ฉบับ":"อ่านเอกสารและโน้ต"}</h2><button onClick={()=>setCompare([])}>ปิดพื้นที่อ่าน</button></div><div className={s.readers}>{compare.map(id=>{const x=items.find(x=>x.id===id);if(!x)return null;return <article key={id}><h3>{x.title}</h3><p>{x.section} · {lawStatuses[x.status]}</p>{x.highlight&&<mark className={s.highlight}>หน้า {x.page} · {x.highlight}</mark>}<p className={s.notes}>{x.notes}</p>{source(x)?<><a href={source(x)} target="_blank" rel="noreferrer">เปิดต้นฉบับในแท็บใหม่ ↗</a>{x.fileName?<iframe title={x.title} src={source(x)}/>:<p>เปิดเว็บต้นฉบับในแท็บใหม่เพื่ออ่าน</p>}</>:<p>รายการนี้มีเฉพาะบันทึก ยังไม่มีไฟล์หรือลิงก์</p>}</article>;})}</div></section>}
 <p className={s.footnote}>สถานะกฎหมายเป็นข้อมูลที่ผู้ใช้ตรวจและบันทึกเอง • ค้นจากข้อมูลและโน้ต ยังไม่ค้นข้อความภายใน PDF • ไฮไลท์เป็นบันทึกประเด็นพร้อมเลขหน้า ไม่แก้ไขไฟล์ต้นฉบับ</p>
 {formOpen&&<dialog ref={dialog} className={s.dialog} onCancel={e=>{e.preventDefault();close();}}><form onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);run(async()=>{await saveLegalReference(data);setItems(await listLegalReferences());window.dispatchEvent(new Event("sarabun-library-updated"));setFormOpen(false);setMessage("บันทึกเข้าคลังแล้ว ไฟล์อยู่ในเครื่อง กดอัปโหลด Drive ที่รายการเมื่อต้องการ");});}}><div className={s.readerHeader}><h2>{editing?"แก้ไขเอกสาร":"เพิ่มเข้าคลัง"}</h2><button type="button" aria-label="ปิดฟอร์ม" onClick={close}><X/></button></div>{message&&<p role="alert">{message}</p>}<fieldset disabled={pending} className={s.form}>{editing&&<><input type="hidden" name="id" value={editing.id}/><input type="hidden" name="updatedAt" value={editing.updatedAt}/></>}
 <label className={s.wide}>ชื่อกฎหมาย / ระเบียบ / หนังสือเวียน<input required name="title" maxLength={300} defaultValue={editing?.title}/></label><label>หมวดหมู่<input required name="category" list="law-categories" maxLength={100} defaultValue={editing?.category||"อื่น ๆ"}/><datalist id="law-categories">{categories.map(c=><option key={c} value={c}/>)}</datalist></label><label>ปีฉบับ (พ.ศ.)<input name="year" pattern="[0-9]{4}" placeholder="เช่น 2569" defaultValue={editing?.year}/></label><label>มาตรา / ข้อ / เลขหนังสือ<input name="section" maxLength={300} defaultValue={editing?.section}/></label><label>สถานะที่ตรวจสอบ<select name="status" defaultValue={editing?.status||"unchecked"}>{Object.entries(lawStatuses).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className={s.wide}>แท็กคำค้น (คั่นด้วยจุลภาค)<input name="tags" maxLength={1000} placeholder="ประชุม, เบิกจ่าย, เทศบาล" defaultValue={editing?.tags}/></label><label className={s.wide}>โน้ตสรุป / ใช้กับงานอะไร / วันที่และแหล่งตรวจสอบ<textarea name="notes" rows={3} maxLength={10000} defaultValue={editing?.notes}/></label><label className={s.wide}>ประเด็นไฮไลท์ / ข้อความสำคัญ<textarea name="highlight" rows={3} maxLength={5000} defaultValue={editing?.highlight}/></label><label>หน้าที่ต้องการเปิดอ่าน<input type="number" name="page" min={1} max={100000} defaultValue={editing?.page||1}/></label><label>ลิงก์ต้นฉบับ<input type="url" name="url" defaultValue={editing?.url}/></label><label className={s.wide}>แนบ PDF ไม่เกิน 10 MB<input type="file" name="file" accept="application/pdf,.pdf"/>{editing?.fileName&&<small>ไฟล์ปัจจุบัน: {editing.fileName} — ไม่เลือกไฟล์ใหม่จะเก็บไฟล์เดิม</small>}</label><p className={s.wide}>Drive จัดเก็บ: คลังกฎหมายและระเบียบ / หมวดหมู่ / ปีฉบับ ไฟล์สืบทอดสิทธิ์ของโฟลเดอร์ปลายทาง</p><button className={`primary ${s.wide}`} disabled={pending}>{pending?"กำลังบันทึก…":"บันทึกเข้าคลัง"}</button></fieldset></form></dialog>}
 </main>;
}
