"use client";
import { useEffect,useRef,useState,useTransition,type ReactNode } from "react";
import { CalendarDays,ChevronLeft,ChevronRight,Clock,DoorOpen,Plus,RefreshCw,Search,Settings2,Users,X } from "lucide-react";
import { today,thaiDate,type SavedDraft } from "@/lib/document";
import { clashes,shiftDate,type Room,type RoomInput,type Booking,type BookingInput } from "@/lib/booking";
import { getBookings,writeBooking,writeRoom,cancelRoomBooking } from "@/app/booking-actions";
import s from "./meeting-bookings.module.css";

function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){
 const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{ref.current?.showModal();},[]);
 return <dialog ref={ref} className={s.dialog} onCancel={e=>{e.preventDefault();onClose();}} aria-label={title}>
  <header><h2>{title}</h2><button type="button" aria-label="ปิดหน้าต่าง" onClick={onClose}><X size={20}/></button></header>{children}
 </dialog>;
}
type Props={initial:{rooms:Room[];bookings:Booking[]};documents:SavedDraft[];onOpenDocument:(d:SavedDraft)=>void};
export function MeetingBookings({initial,documents,onOpenDocument}:Props){
 const [data,setData]=useState(initial),[date,setDate]=useState(today()),[week,setWeek]=useState(false),[roomFilter,setRoomFilter]=useState("all"),[query,setQuery]=useState(""),[showCancelled,setShowCancelled]=useState(false);
 const [booking,setBooking]=useState<BookingInput|null>(null),[editing,setEditing]=useState<Booking|null>(null),[room,setRoom]=useState<RoomInput|null>(null),[editingRoom,setEditingRoom]=useState<Room|null>(null);
 const [cancelling,setCancelling]=useState<Booking|null>(null),[reason,setReason]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState(""),[pending,start]=useTransition();
 const days=Array.from({length:week?7:1},(_,i)=>shiftDate(date,i));
 const results=data.bookings.filter(b=>days.includes(b.date)&&(roomFilter==="all"||b.roomId===roomFilter)&&(showCancelled||b.status!=="cancelled")&&[b.title,b.organizer,b.department].join(" ").toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()));
 const selectedRoom=data.rooms.find(r=>r.id===booking?.roomId);
 const conflicts=booking&&selectedRoom?clashes(data.bookings,booking.roomId,booking.date,booking.start,booking.end,selectedRoom.bufferMinutes,editing?.id):[];
 const roomNames=new Map(data.rooms.map(r=>[r.id,r.name]));
 function run(job:()=>Promise<void>){setError("");start(async()=>{try{await job();}catch(e){setError(e instanceof Error?e.message:"ติดต่อระบบไม่สำเร็จ");}});}
 function close(){if(pending)return;if(confirm("ปิดหน้าต่างและละทิ้งข้อมูลที่ยังไม่บันทึกหรือไม่?")){setBooking(null);setRoom(null);setCancelling(null);setError("");}}
 function refresh(){run(async()=>{setData(await getBookings());setNotice("อัปเดตตารางแล้ว");});}
 function createBooking(roomId?:string){setEditing(null);setError("");setBooking({roomId:roomId||data.rooms.find(r=>r.active)?.id||"",title:"",organizer:"",department:"",contact:"",date,start:"09:00",end:"10:00",attendees:1,documentId:"",notes:""});}
 function update<K extends keyof BookingInput>(key:K,value:BookingInput[K]){setBooking(b=>b?{...b,[key]:value}:null);}
 function roomUpdate<K extends keyof RoomInput>(key:K,value:RoomInput[K]){setRoom(r=>r?{...r,[key]:value}:null);}
 const errorBox=error?<p role="alert" className={s.error}>{error}</p>:null;
 return <main className={`page-main ${s.root}`}>
  <header className={s.heading}><div><span>MEETING SPACE</span><h1>จองห้องประชุม</h1><p>เลือกห้องให้พร้อม แล้วเริ่มงานได้ตรงเวลา</p></div><button className="primary" disabled={!data.rooms.some(r=>r.active)} onClick={()=>createBooking()}><Plus size={18}/>จองห้อง</button></header>
  <div className={s.metrics}><div><DoorOpen size={20}/><strong>{data.rooms.filter(r=>r.active).length}</strong><span>ห้องเปิดรับจอง</span></div><div><CalendarDays size={20}/><strong>{data.bookings.filter(b=>b.date===date&&b.status==="booked").length}</strong><span>การจองวันที่เลือก</span></div><div><Clock size={20}/><span>เวลาไทย • จองภายในวันเดียว</span></div></div>
  <section className={s.roomSection}><div className={s.sectionTitle}><h2>ห้องประชุม</h2><button onClick={()=>{setRoom({name:"",location:"",capacity:20,equipment:"",bufferMinutes:15,active:true});setEditingRoom(null);setError("");}}><Plus size={16}/>เพิ่มห้อง</button></div>
  <div className={s.rooms}>{data.rooms.map(r=><article key={r.id} className={s.room}><div className={s.roomTop}><DoorOpen size={22}/><button aria-label={`ตั้งค่า ${r.name}`} onClick={()=>{setRoom(r);setEditingRoom(r);setError("");}}><Settings2 size={17}/></button></div><h3>{r.name}</h3><p>{r.location||"ยังไม่ระบุสถานที่"}</p><div><Users size={15}/>{r.capacity} คน <span>·</span> เก็บห้อง {r.bufferMinutes} นาที</div><small>{r.equipment||"ยังไม่ระบุอุปกรณ์"}</small><button className="secondary" disabled={!r.active} onClick={()=>createBooking(r.id)}>{r.active?"เลือกห้องนี้":"ปิดรับจอง"}</button></article>)}</div>
  {!data.rooms.length&&<div className={s.empty}><DoorOpen size={30}/><h3>เริ่มด้วยห้องประชุมของหน่วยงาน</h3><p>เพิ่มชื่อห้อง จำนวนที่นั่ง และอุปกรณ์ ก่อนเปิดรับจอง</p></div>}</section>
  <section className={s.schedule}><div className={s.toolbar}><div className={s.dayPicker}><button aria-label="ช่วงก่อนหน้า" onClick={()=>setDate(shiftDate(date,week?-7:-1))}><ChevronLeft size={18}/></button><input aria-label="วันที่ตารางจอง" type="date" value={date} onChange={e=>{if(e.target.value)setDate(e.target.value);}}/><button aria-label="ช่วงถัดไป" onClick={()=>setDate(shiftDate(date,week?7:1))}><ChevronRight size={18}/></button><button onClick={()=>setDate(today())}>วันนี้</button></div><div className={s.switcher}><button aria-pressed={!week} onClick={()=>setWeek(false)}>วัน</button><button aria-pressed={week} onClick={()=>setWeek(true)}>7 วัน</button></div><button aria-label="รีเฟรชตารางจอง" disabled={pending} onClick={refresh}><RefreshCw size={17}/></button></div>
  <div className={s.filters}><div className={s.search}><Search size={17}/><input aria-label="ค้นหาการจอง" placeholder="ค้นหาเรื่อง ผู้จอง หรือหน่วยงาน" value={query} onChange={e=>setQuery(e.target.value)}/></div><select aria-label="กรองห้องประชุม" value={roomFilter} onChange={e=>setRoomFilter(e.target.value)}><option value="all">ทุกห้อง</option>{data.rooms.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><label className={s.check}><input type="checkbox" checked={showCancelled} onChange={e=>setShowCancelled(e.target.checked)}/>แสดงรายการยกเลิก</label></div>
  {days.map(day=><section className={s.day} key={day}><h3>{thaiDate(day)}</h3>{results.filter(b=>b.date===day).map(b=><article key={b.id} className={`${s.event} ${b.status==="cancelled"?s.cancelled:""}`}><div className={s.eventTime}><strong>{b.start}–{b.end}</strong><small>เก็บห้องต่อ {b.bufferMinutes} นาที</small></div><div className={s.eventBody}><h4>{b.title}</h4><p>{roomNames.get(b.roomId)} · {b.attendees} คน · {b.organizer}</p><small>{b.status==="cancelled"?`ยกเลิก: ${b.cancellationReason}`:b.department}</small></div><div className={s.eventActions}>{b.documentId&&documents.some(d=>d.id===b.documentId)&&<button onClick={()=>onOpenDocument(documents.find(d=>d.id===b.documentId)!)}>หนังสือ</button>}{b.status==="booked"&&<><button onClick={()=>{setEditing(b);setBooking(b);setError("");}}>รายละเอียด / แก้ไข</button><button className={s.danger} onClick={()=>{setCancelling(b);setReason("");setError("");}}>ยกเลิก</button></>}</div></article>)}{!results.some(b=>b.date===day)&&<p className={s.noBookings}>ไม่มีรายการตรงกับการค้นหาในวันนี้</p>}</section>)}
  </section>{notice&&<p role="status" className={s.notice}>{notice}</p>}{!booking&&!room&&!cancelling&&errorBox}
  {booking&&<Modal title={editing?"แก้ไขการจอง":"จองห้องประชุม"} onClose={close}><form onSubmit={e=>{e.preventDefault();run(async()=>{const r=await writeBooking(booking,editing?.id,editing?.version);if(!r.ok){setError(r.error);setData(await getBookings());return;}setData(r);setDate(booking.date);setRoomFilter("all");setQuery("");setBooking(null);setNotice("บันทึกการจองแล้ว");});}}><fieldset disabled={pending}>
   <label>หัวข้อการประชุม *<input autoFocus required maxLength={300} value={booking.title} onChange={e=>update("title",e.target.value)}/></label><div className={s.fields}><label>จำนวนผู้เข้าร่วม *<input required type="number" min="1" max="10000" value={booking.attendees} onChange={e=>update("attendees",Number(e.target.value))}/></label><label>ห้องประชุม *<select aria-label="ห้องที่จอง" required value={booking.roomId} onChange={e=>update("roomId",e.target.value)}><option value="">เลือกห้อง</option>{data.rooms.map(r=><option disabled={!r.active||r.capacity<booking.attendees} key={r.id} value={r.id}>{r.name} · {r.capacity} คน{!r.active?" (ปิดรับจอง)":r.capacity<booking.attendees?" (ที่นั่งไม่พอ)":""}</option>)}</select></label><label>วันที่ประชุม *<input required type="date" value={booking.date} onChange={e=>update("date",e.target.value)}/></label><div className={s.fields}><label>เริ่ม *<input required type="time" value={booking.start} onChange={e=>update("start",e.target.value)}/></label><label>สิ้นสุด *<input required type="time" value={booking.end} onChange={e=>update("end",e.target.value)}/></label></div></div>
   <div className={s.availability} aria-live="polite">{selectedRoom?<><strong>{selectedRoom.name}</strong><p>{selectedRoom.equipment||"ไม่ได้ระบุอุปกรณ์"} · เว้นเวลาจัดเก็บหลังประชุม {selectedRoom.bufferMinutes} นาที</p>{conflicts.length?<p className={s.danger}>เวลาชนกับ {conflicts.map(b=>`${b.start}–${b.end} ${b.title}`).join(" / ")}</p>:<p>ยังไม่พบการจองซ้อนในตารางที่โหลดมา ระบบจะตรวจอีกครั้งเมื่อบันทึก</p>}{booking.attendees>selectedRoom.capacity&&<p className={s.danger}>จำนวนผู้เข้าร่วมเกินความจุห้อง</p>}</>:"เลือกห้องและเวลาเพื่อดูรายการที่ทับซ้อน"}</div>
   <div className={s.fields}><label>ผู้จอง / ผู้ประสานงาน *<input required maxLength={200} value={booking.organizer} onChange={e=>update("organizer",e.target.value)}/></label><label>หน่วยงาน<input maxLength={300} value={booking.department} onChange={e=>update("department",e.target.value)}/></label></div><label>โทรศัพท์ / ช่องทางติดต่อ<input maxLength={300} value={booking.contact} onChange={e=>update("contact",e.target.value)}/></label><label>หนังสือเชิญประชุม / เอกสารที่เกี่ยวข้อง<select value={booking.documentId} onChange={e=>update("documentId",e.target.value)}><option value="">ไม่เชื่อมโยง</option>{documents.map(d=><option key={d.id} value={d.id}>{d.number} {d.subject}</option>)}</select></label><label>วาระ / การจัดห้อง / สิ่งที่ต้องเตรียม<textarea rows={3} maxLength={10000} value={booking.notes} onChange={e=>update("notes",e.target.value)}/></label>{errorBox}<footer><button className="secondary" type="button" onClick={refresh}>ตรวจตารางล่าสุด</button><button className="primary" type="submit">{pending?"กำลังบันทึก…":"บันทึกการจอง"}</button></footer></fieldset></form></Modal>}
  {room&&<Modal title={editingRoom?"ตั้งค่าห้องประชุม":"เพิ่มห้องประชุม"} onClose={close}><form onSubmit={e=>{e.preventDefault();run(async()=>{const r=await writeRoom(room,editingRoom?.id,editingRoom?.version);if(!r.ok){setError(r.error);return;}setData(r);setRoom(null);setNotice("บันทึกห้องประชุมแล้ว");});}}><fieldset disabled={pending}><label>ชื่อห้อง *<input autoFocus required maxLength={120} value={room.name} onChange={e=>roomUpdate("name",e.target.value)}/></label><label>อาคาร / ชั้น / ที่ตั้ง<input maxLength={300} value={room.location} onChange={e=>roomUpdate("location",e.target.value)}/></label><div className={s.fields}><label>จำนวนที่นั่ง *<input type="number" required min="1" max="10000" value={room.capacity} onChange={e=>roomUpdate("capacity",Number(e.target.value))}/></label><label>เวลาจัดเก็บหลังประชุม (นาที)<input required type="number" min="0" max="120" value={room.bufferMinutes} onChange={e=>roomUpdate("bufferMinutes",Number(e.target.value))}/></label></div><label>อุปกรณ์ประจำห้อง<textarea rows={3} maxLength={2000} placeholder="เช่น จอภาพ ไมโครโฟน ระบบประชุมออนไลน์" value={room.equipment} onChange={e=>roomUpdate("equipment",e.target.value)}/></label><label className={s.check}><input type="checkbox" checked={room.active} onChange={e=>roomUpdate("active",e.target.checked)}/>เปิดรับจอง</label><p className={s.help}>การปรับห้องมีผลกับการจองใหม่และการแก้ไขครั้งถัดไป การจองเดิมยังคงอยู่</p>{errorBox}<footer><button className="primary">{pending?"กำลังบันทึก…":"บันทึกห้อง"}</button></footer></fieldset></form></Modal>}
  {cancelling&&<Modal title="ยกเลิกการจอง" onClose={close}><form onSubmit={e=>{e.preventDefault();run(async()=>{const r=await cancelRoomBooking(cancelling.id,cancelling.version,reason);if(!r.ok){setError(r.error);return;}setData(r);setCancelling(null);setNotice("ยกเลิกแล้ว ช่วงเวลานี้เปิดให้จองใหม่ได้");});}}><fieldset disabled={pending}><h3>{cancelling.title}</h3><p>{thaiDate(cancelling.date)} · {cancelling.start}–{cancelling.end}</p><label>เหตุผล *<textarea autoFocus required maxLength={1000} rows={3} value={reason} onChange={e=>setReason(e.target.value)}/></label>{errorBox}<footer><button className="primary" type="submit">ยืนยันยกเลิกการจอง</button></footer></fieldset></form></Modal>}
 </main>;
}
