"use client";
import { useState,useTransition } from "react";
import { Plus,Search,ClipboardList,CalendarDays,Users,Package,Archive,Inbox,Send,Download,X,RefreshCw,ExternalLink,Trash2 } from "lucide-react";
import { officeKinds,officeSchema,officeStatuses,routineTasks,type OfficeKind,type OfficeItem,type OfficeInput } from "@/lib/office";
import { today,type SavedDraft } from "@/lib/document";
import { getOfficeItems,saveOfficeItem,removeOfficeItem } from "@/app/office-actions";
import s from "./office-workspace.module.css";
const icons={incoming:Inbox,outgoing:Send,task:ClipboardList,meeting:CalendarDays,contact:Users,supplies:Package,archive:Archive};
export function OfficeWorkspace({initialItems,documents,onOpenDocument}:{initialItems:OfficeItem[];documents:SavedDraft[];onOpenDocument:(d:SavedDraft)=>void}){
 const [items,setItems]=useState(initialItems),[kind,setKind]=useState<OfficeKind>("task"),[query,setQuery]=useState(""),[filter,setFilter]=useState("all"),[form,setForm]=useState<OfficeInput|null>(null),[editing,setEditing]=useState<OfficeItem|null>(null),[message,setMessage]=useState(""),[pending,start]=useTransition();
 const day=today(),active=items.filter(i=>i.status!=="done"&&!["contact","supplies","archive"].includes(i.kind)),late=active.filter(i=>i.due&&i.due<day),soon=active.filter(i=>i.due&&i.due>=day&&i.due<=new Date(Date.now()+7*86400000).toISOString().slice(0,10));
 const low=items.filter(i=>i.kind==="supplies"&&i.quantity<=i.minimum);
 const normalize=(v:string)=>v.replace(/[๐-๙]/g,c=>String("๐๑๒๓๔๕๖๗๘๙".indexOf(c))).toLocaleLowerCase();
 const shown=items.filter(i=>(filter==="active"?active.some(x=>x.id===i.id):filter==="late"?late.some(x=>x.id===i.id):filter==="soon"?soon.some(x=>x.id===i.id):filter==="low"?low.some(x=>x.id===i.id):i.kind===kind&&(filter==="all"||i.status===filter))&&normalize([i.title,i.number,i.party,i.owner,i.notes].join(" ")).includes(normalize(query)));
 function run(fn:()=>Promise<void>){start(async()=>{try{await fn();}catch(e){setMessage(e instanceof Error?e.message:"ติดต่อเซิร์ฟเวอร์ไม่สำเร็จ");}});}

 function newForm(k:OfficeKind,title=""){setEditing(null);setForm({...officeSchema.parse({kind:k,title:title||"งานใหม่",date:day}),title});}
 function set<K extends keyof OfficeInput>(key:K,value:OfficeInput[K]){setForm(f=>f?{...f,[key]:value}:f);}
 function exportCsv(){const rows=[["หมวด","เรื่อง","เลขที่","หน่วยงาน/สถานที่","ผู้รับผิดชอบ","วันที่","ครบกำหนด","สถานะ","คงเหลือ","หน่วย","หมายเหตุ"],...shown.map(i=>[officeKinds[i.kind],i.title,i.number,i.party,i.owner,i.date,i.due,officeStatuses[i.status],String(i.quantity),i.unit,i.notes])];const cell=(v:string)=>'"'+(/^[=+@\-\t\r\n]/.test(v)?"'":"")+v.replace(/"/g,'""')+'"';const url=URL.createObjectURL(new Blob(["\ufeff"+rows.map(r=>r.map(cell).join(",")).join("\r\n")],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=`งานธุรการ-${day}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <main className={`page-main ${s.root}`}>
 <header className={s.heading}><div><span>พื้นที่ปฏิบัติงานเทศบาล</span><h1>งานธุรการ</h1><p>รับเรื่อง • ประสานงาน • ติดตาม • จัดเก็บ</p></div><button className="primary" onClick={()=>newForm(kind)}><Plus size={18}/>เพิ่มรายการ</button></header>
 <div className={s.stats}>{[{label:"งานกำลังดำเนินการ",value:active.length,f:"active"},{label:"เกินกำหนด",value:late.length,f:"late"},{label:"ครบกำหนดใน 7 วัน",value:soon.length,f:"soon"},{label:"วัสดุถึงจุดเติม",value:low.length,f:"low"}].map(x=><button key={x.f} onClick={()=>{setFilter(x.f);if(x.f==="all")setKind("task");}}><strong>{x.value}</strong><span>{x.label}</span></button>)}</div>
 <nav className={s.tabs} aria-label="หมวดงานธุรการ">{Object.entries(officeKinds).map(([key,label])=>{const Icon=icons[key as OfficeKind];return <button key={key} aria-pressed={kind===key&&!["active","late","soon","low"].includes(filter)} onClick={()=>{setKind(key as OfficeKind);setFilter("all");}}><Icon size={18}/>{label}<small>{items.filter(i=>i.kind===key).length}</small></button>;})}</nav>
 <section className={s.panel}><div className={s.toolbar}><div className={s.search}><Search size={17}/><input aria-label="ค้นหางานธุรการ" placeholder="ค้นหาเรื่อง เลขที่ หน่วยงาน หรือผู้รับผิดชอบ" value={query} onChange={e=>setQuery(e.target.value)}/></div><select aria-label="กรองสถานะงาน" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">ทุกสถานะในหมวด</option>{Object.entries(officeStatuses).map(([v,t])=><option key={v} value={v}>{t}</option>)}<option value="active">งานค้างทุกหมวด</option><option value="late">เกินกำหนดทุกหมวด</option><option value="soon">ใกล้ครบกำหนดทุกหมวด</option><option value="low">วัสดุถึงจุดเติม</option></select><button title="รีเฟรชงาน" aria-label="รีเฟรชงาน" disabled={pending} onClick={()=>run(async()=>setItems(await getOfficeItems()))}><RefreshCw size={17}/></button><button disabled={!shown.length} onClick={exportCsv}><Download size={17}/>CSV</button></div>
 <div className={s.table}><table><thead><tr><th>รายการ / เลขที่</th><th>หน่วยงาน / ผู้รับผิดชอบ</th><th>{kind==="supplies"?"คงเหลือ / จุดเติม":"วันที่ / กำหนดเสร็จ"}</th><th>สถานะ</th><th>เชื่อมโยง</th></tr></thead><tbody>{shown.map(i=><tr key={i.id}><td><button className={s.title} onClick={()=>{setEditing(i);setForm(officeSchema.parse(i));}}>{i.priority==="urgent"&&<b className={s.urgent}>ด่วน</b>}{i.title}</button><small>{i.number||"ไม่ระบุเลขที่"} · {officeKinds[i.kind]}</small></td><td>{i.party||"—"}<small>{i.owner||"ยังไม่มอบหมาย"}</small></td><td>{i.kind==="supplies"?`${i.quantity} ${i.unit} / เติมที่ ${i.minimum}`:i.date||"—"}{i.due&&<small className={i.due<day&&i.status!=="done"?s.overdue:undefined}>ครบกำหนด {i.due}</small>}</td><td><span className={i.status==="done"?s.done:s.badge}>{officeStatuses[i.status]}</span></td><td><div className={s.links}>{i.documentId&&documents.some(d=>d.id===i.documentId)&&<button onClick={()=>onOpenDocument(documents.find(d=>d.id===i.documentId)!)}>หนังสือ</button>}{i.url&&<a href={i.url} target="_blank" rel="noreferrer" aria-label={`เปิดลิงก์ ${i.title}`}><ExternalLink size={17}/></a>}</div></td></tr>)}</tbody></table></div>
 {!shown.length&&<div className={s.empty}><ClipboardList size={32}/><h3>พร้อมเริ่มจัดระเบียบงาน</h3><p>{query||filter!=="all"?"ไม่พบรายการที่ตรงกับตัวกรอง":"เพิ่มข้อมูลจริง หรือเลือกงานประจำด้านล่างเป็นต้นแบบ"}</p><button className="secondary" onClick={()=>newForm(kind)}>เพิ่ม{officeKinds[kind]}</button></div>}<footer className={s.footer}>{shown.length} รายการ · บันทึกในฐานข้อมูลของระบบ</footer></section>
 <section className={s.routines}><div><h2>งานประจำที่เริ่มได้ทันที</h2><p>กดเพื่อเปิดฟอร์ม ตรวจข้อมูลแล้วบันทึกเป็นงานของคุณ</p></div><div>{routineTasks.map(title=><button key={title} onClick={()=>newForm("task",title)}><Plus size={15}/>{title}</button>)}</div></section>
 {message&&<div className={s.message} role="status">{message}<button aria-label="ปิดข้อความ" onClick={()=>setMessage("")}><X size={16}/></button></div>}
 {form&&<div className={s.overlay}><section className={s.dialog} role="dialog" aria-modal="true" aria-labelledby="office-title"><header><div><small>{officeKinds[form.kind]}</small><h2 id="office-title">{editing?"แก้ไขรายการ":"เพิ่มรายการใหม่"}</h2></div><button aria-label="ปิดฟอร์มงาน" disabled={pending} onClick={()=>{if(confirm("ปิดฟอร์มและละทิ้งข้อมูลที่ยังไม่บันทึกหรือไม่?"))setForm(null);}}><X size={20}/></button></header><form onSubmit={e=>{e.preventDefault();run(async()=>{const r=await saveOfficeItem(form,editing?.id,editing?.version);if(!r.ok){setMessage(r.error);return;}setItems(r.items);setForm(null);setMessage("บันทึกรายการแล้ว");});}}>
 <label>ชื่อเรื่อง / ชื่องาน / ชื่อรายการ *<input autoFocus required maxLength={300} value={form.title} onChange={e=>set("title",e.target.value)}/></label><div className={s.fields}>
 <label>{["incoming","outgoing"].includes(form.kind)?"เลขทะเบียน (ตามทะเบียนหน่วยงาน)":"เลขอ้างอิง / รหัสรายการ"}<input value={form.number} onChange={e=>set("number",e.target.value)}/></label><label>{form.kind==="meeting"?"สถานที่ / ห้องประชุม":form.kind==="contact"?"หน่วยงาน / สังกัด":form.kind==="archive"?"ที่เก็บแฟ้ม / ตู้ / ชั้น":"จาก / ถึง / หน่วยงานที่เกี่ยวข้อง"}<input value={form.party} onChange={e=>set("party",e.target.value)}/></label>
 <label>{form.kind==="contact"?"ผู้ติดต่อ":"ผู้รับผิดชอบ / ผู้ประสานงาน"}<input value={form.owner} onChange={e=>set("owner",e.target.value)}/></label><label>ความสำคัญ<select value={form.priority} onChange={e=>set("priority",e.target.value as OfficeInput["priority"])}><option value="normal">ปกติ</option><option value="urgent">ต้องเร่งดำเนินการ</option></select></label>
 <label>{form.kind==="meeting"?"วันที่ประชุม":"วันที่บันทึก / รับ / ส่ง"}<input type="date" value={form.date} onChange={e=>set("date",e.target.value)}/></label><label>{form.kind==="archive"?"วันทบทวนแฟ้ม":"กำหนดเสร็จ / นัดติดตาม"}<input type="date" value={form.due} onChange={e=>set("due",e.target.value)}/></label>
 {form.kind==="supplies"&&<><label>จำนวนคงเหลือ<input type="number" min="0" step="any" value={form.quantity} onChange={e=>set("quantity",Number(e.target.value))}/></label><label>จุดแจ้งเตือนเติมวัสดุ<input type="number" min="0" step="any" value={form.minimum} onChange={e=>set("minimum",Number(e.target.value))}/></label><label>หน่วยนับ<input value={form.unit} onChange={e=>set("unit",e.target.value)}/></label></>}
 <label>สถานะ<select value={form.status} onChange={e=>set("status",e.target.value as OfficeInput["status"])}>{Object.entries(officeStatuses).map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label><label>เชื่อมกับหนังสือในระบบ<select value={form.documentId} onChange={e=>set("documentId",e.target.value)}><option value="">ไม่เชื่อมโยง</option>{documents.map(d=><option key={d.id} value={d.id}>{d.number} {d.subject}</option>)}</select></label></div>
 <label>ลิงก์ Drive / เอกสาร / เว็บไซต์<input type="url" placeholder="https://" value={form.url} onChange={e=>set("url",e.target.value)}/></label><label>{form.kind==="meeting"?"เวลา / ผู้เข้าร่วม / วาระ / มติ / งานติดตาม":form.kind==="contact"?"โทรศัพท์ / อีเมล / ช่องทางติดต่อ":"รายละเอียด / ขั้นตอน / ผลดำเนินการ"}<textarea rows={5} value={form.notes} onChange={e=>set("notes",e.target.value)}/></label>
 <footer>{editing&&<button type="button" disabled={pending} onClick={()=>{if(confirm("ลบรายการงานนี้หรือไม่? หนังสือที่เชื่อมไว้ยังคงอยู่"))run(async()=>{const r=await removeOfficeItem(editing.id,editing.version);if(!r.ok){setMessage(r.error);return;}setItems(r.items);setForm(null);setMessage("ลบรายการแล้ว");});}}><Trash2 size={16}/>ลบรายการ</button>}<button className="primary" disabled={pending} type="submit">{pending?"กำลังบันทึก…":"บันทึกรายการ"}</button></footer></form></section></div>}
 </main>;
}
