"use client";
import { useEffect,useRef,useState,useTransition } from "react";
import { CalendarDays,ChevronLeft,ChevronRight,Plus,RefreshCw,X } from "lucide-react";
import { blankEvent,eventKinds,onDay,type CalendarEvent,type CalendarInput } from "@/lib/calendar";
import { today,thaiDate,type SavedDraft } from "@/lib/document";
import { shiftDate,type Booking } from "@/lib/booking";
import type { OfficeItem } from "@/lib/office";
import { getCalendar,saveCalendar } from "@/app/calendar-actions";
import s from "./work-calendar.module.css";
export function WorkCalendar({initial,office,documents,bookings,onOpenDocument}:{initial:CalendarEvent[];office:OfficeItem[];documents:SavedDraft[];bookings:Booking[];onOpenDocument:(d:SavedDraft)=>void}){
 const [events,setEvents]=useState(initial),[month,setMonth]=useState(today().slice(0,7)),[selected,setSelected]=useState(today()),[query,setQuery]=useState(""),[kind,setKind]=useState("all"),[cancelled,setCancelled]=useState(false),[form,setForm]=useState<CalendarInput|null>(null),[editing,setEditing]=useState<CalendarEvent|null>(null),[docSearch,setDocSearch]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState(""),[pending,start]=useTransition();
 const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(form&&!dialog.current?.open)dialog.current?.showModal();},[form]);
 const normalized=(v:string)=>v.toLowerCase().replace(/[๐-๙]/g,c=>String("๐๑๒๓๔๕๖๗๘๙".indexOf(c)));
 const matching=events.filter(e=>(cancelled||e.status!=="cancelled")&&(kind==="all"||kind===e.kind)&&normalized([e.title,e.owner,e.location,documents.find(d=>d.id===e.documentId)?.subject||"",office.find(o=>o.id===e.sourceOfficeId)?.number||""].join(" ")).includes(normalized(query)));
 const rooms=bookings.filter(b=>b.status==="booked"&&(kind==="all"||kind==="room")&&normalized(b.title+" "+b.organizer).includes(normalized(query)));
 const first=month+"-01",offset=new Date(first+"T12:00:00Z").getUTCDay(),days=Array.from({length:42},(_,i)=>shiftDate(first,i-offset));
 function move(n:number){const d=new Date(first+"T12:00:00Z");d.setUTCMonth(d.getUTCMonth()+n);setMonth(d.toISOString().slice(0,7));setSelected(d.toISOString().slice(0,10));}
 function open(e?:CalendarEvent){setError("");setDocSearch("");setEditing(e||null);setForm(e?structuredClone(e):blankEvent(selected));}
 function close(){if(pending)return;if(form&&JSON.stringify(form)!==JSON.stringify(editing||blankEvent(selected))&&!confirm("ปิดโดยไม่บันทึกการแก้ไขหรือไม่?"))return;setForm(null);}
 function set<K extends keyof CalendarInput>(key:K,value:CalendarInput[K]){setForm(f=>f?{...f,[key]:value}:f);}
 function run(job:()=>Promise<void>){start(async()=>{try{await job();}catch(e){setError(e instanceof Error?e.message:"ติดต่อเซิร์ฟเวอร์ไม่สำเร็จ");}});}
 function documentLinks(id:string){const d=documents.find(d=>d.id===id);return d?<div className={s.links}><button type="button" onClick={()=>onOpenDocument(d)}>เปิดหนังสือ: {d.subject||"ไม่ระบุเรื่อง"}</button>{d.driveFileId&&<a href={`https://drive.google.com/file/d/${encodeURIComponent(d.driveFileId)}/view`} target="_blank" rel="noreferrer">เปิดไฟล์ Drive{d.syncedVersion!==d.version?" (ฉบับก่อนซิงก์)":""}</a>}</div>:id?<p>หนังสือที่เชื่อมโยงถูกลบหรือไม่พร้อมใช้งาน</p>:null;}
 return <main className={`page-main ${s.root}`}><header className={s.header}><div><span className={s.eyebrow}>WORK CALENDAR</span><h1>ปฏิทินงาน</h1><p>ทุกนัดหมาย พร้อมหนังสือที่เกี่ยวข้องในที่เดียว</p></div><button className="primary" onClick={()=>open()}><Plus size={18}/>เพิ่มนัดหมาย</button></header>
 {error&&!form&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <section className={s.panel}><div className={s.toolbar}><div><button aria-label="เดือนก่อน" onClick={()=>move(-1)}><ChevronLeft/></button><h2>{new Date(first+"T12:00:00Z").toLocaleDateString("th-TH",{month:"long",year:"numeric",timeZone:"Asia/Bangkok"})}</h2><button aria-label="เดือนถัดไป" onClick={()=>move(1)}><ChevronRight/></button><button onClick={()=>{setMonth(today().slice(0,7));setSelected(today());}}>วันนี้</button></div><button disabled={pending} onClick={()=>run(async()=>{setEvents(await getCalendar());setNotice("โหลดนัดหมายล่าสุดแล้ว");})}><RefreshCw size={16}/>โหลดนัดหมาย</button></div>
 <div className={s.filters}><input aria-label="ค้นหานัดหมาย" placeholder="ค้นหาเรื่อง ผู้รับผิดชอบ สถานที่ หรือเลขหนังสือรับ" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="ประเภทนัดหมาย" value={kind} onChange={e=>setKind(e.target.value)}><option value="all">ทุกประเภท</option>{Object.entries(eventKinds).map(([k,v])=><option key={k} value={k}>{v}</option>)}<option value="room">จองห้องประชุม</option></select><label><input type="checkbox" checked={cancelled} onChange={e=>setCancelled(e.target.checked)}/>แสดงที่ยกเลิก</label></div>
 <div className={s.scroll}><div className={s.grid}>{["อา.","จ.","อ.","พ.","พฤ.","ศ.","ส."].map(d=><div className={s.weekday} key={d}>{d}</div>)}{days.map(day=>{const list=matching.filter(e=>onDay(e,day)),book=rooms.filter(b=>b.date===day);return <div key={day} className={`${s.day} ${day.slice(0,7)!==month?s.muted:""} ${selected===day?s.selected:""}`}><button className={`${s.date} ${day===today()?s.today:""}`} aria-label={`ดูวันที่ ${thaiDate(day)}`} onClick={()=>setSelected(day)}>{Number(day.slice(-2))}</button>{list.slice(0,3).map(e=><button key={e.id} className={`${s.event} ${s[e.kind]} ${e.status==="cancelled"?s.cancelled:""}`} onClick={()=>{setSelected(day);open(e);}} title={e.title}>{e.allDay?"ทั้งวัน":e.start} {e.title}</button>)}{book.slice(0,2).map(b=><button key={b.id} className={`${s.event} ${s.room}`} onClick={()=>setSelected(day)}>{b.start} {b.title}</button>)}{list.length>3||book.length>2?<button onClick={()=>setSelected(day)}>ดูทั้งหมด {list.length+book.length} รายการ</button>:null}</div>;})}</div></div></section>
 <section className={s.panel}><div className={s.toolbar}><h2><CalendarDays size={20}/>{thaiDate(selected)}</h2><button onClick={()=>open()}><Plus size={16}/>เพิ่มในวันนี้</button></div><div className={s.agenda}>{matching.filter(e=>onDay(e,selected)).map(e=><article key={e.id}><div><span className={s.tag}>{eventKinds[e.kind]} · {e.status==="cancelled"?"ยกเลิก":e.status==="done"?"เสร็จสิ้น":e.allDay?"ทั้งวัน":`${e.start}–${e.end}`}</span><h3>{e.title}</h3><p>{e.location||"ยังไม่ระบุสถานที่"} · {e.owner||"ยังไม่ระบุผู้รับผิดชอบ"}</p>{e.date!==e.endDate&&<p>{thaiDate(e.date)} – {thaiDate(e.endDate)}</p>}{e.notes&&<p className={s.notes}>{e.notes}</p>}{documentLinks(e.documentId)}{e.attachments.map((a,i)=><a className={s.file} key={i} href={a.url} target="_blank" rel="noreferrer">เอกสารแนบ: {a.name} ↗</a>)}</div><button onClick={()=>open(e)}>รายละเอียด / แก้ไข</button></article>)}{rooms.filter(b=>b.date===selected).map(b=><article key={b.id}><div><span className={s.tag}>จองห้องประชุม · {b.start}–{b.end}</span><h3>{b.title}</h3><p>{b.organizer}</p>{documentLinks(b.documentId)}</div><a href="/?view=bookings">จัดการการจอง ↗</a></article>)}{!matching.some(e=>onDay(e,selected))&&!rooms.some(b=>b.date===selected)&&<p>ไม่มีนัดหมายตามตัวกรองในวันนี้ กดเพิ่มในวันนี้เพื่อเริ่มต้น</p>}</div></section>
 <p className={s.footnote}>เวลาไทย • การเพิ่มนัดหมายไม่จองห้องให้อัตโนมัติ • ไฟล์เปิดด้วยสิทธิ์ของบัญชีผู้ใช้</p>
 {form&&<dialog ref={dialog} className={s.dialog} onCancel={e=>{e.preventDefault();close();}}><form onSubmit={e=>{e.preventDefault();run(async()=>{const result=await saveCalendar(form,editing?.id,editing?.version);if(!result.ok){setError(result.error);return;}setEvents(result.events);setSelected(form.date);setMonth(form.date.slice(0,7));setNotice("บันทึกนัดหมายแล้ว");setForm(null);});}}><header className={s.toolbar}><h2>{editing?"รายละเอียดนัดหมาย":"เพิ่มนัดหมาย"}</h2><button type="button" aria-label="ปิด" onClick={close}><X/></button></header>{error&&<p role="alert">{error}</p>}<fieldset disabled={pending} className={s.form}>
 <label className={s.wide}>นำข้อมูลจากทะเบียนหนังสือ / งาน<select value={form.sourceOfficeId} onChange={e=>{const o=office.find(o=>o.id===e.target.value);setForm(f=>f?{...f,sourceOfficeId:e.target.value,...(o?{title:o.title,owner:o.owner,documentId:o.documentId,attachments:o.url?[{name:o.number||o.title,url:o.url}]:[]}: {})}:f);}}><option value="">ไม่เลือกต้นทาง</option>{office.filter(o=>["incoming","outgoing","meeting","task"].includes(o.kind)).map(o=><option key={o.id} value={o.id}>{o.number} {o.title}</option>)}</select><small>ดึงชื่อเรื่อง ผู้รับผิดชอบ และเอกสารมาให้ กรุณาระบุวันนัดตามเนื้อหาหนังสือ</small></label>
 <label className={s.wide}>เรื่อง<input required maxLength={300} value={form.title} onChange={e=>set("title",e.target.value)}/></label><label>ประเภท<select value={form.kind} onChange={e=>set("kind",e.target.value as CalendarInput["kind"])}>{Object.entries(eventKinds).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>สถานะ<select value={form.status} onChange={e=>set("status",e.target.value as CalendarInput["status"])}><option value="scheduled">นัดหมาย</option><option value="done">เสร็จสิ้น</option><option value="cancelled">ยกเลิก</option></select></label>
 <label>วันเริ่ม<input required type="date" value={form.date} onChange={e=>setForm(f=>f?{...f,date:e.target.value,endDate:f.endDate<f.date||f.endDate<e.target.value?e.target.value:f.endDate}:f)}/></label><label>วันสิ้นสุด<input required type="date" min={form.date} value={form.endDate} onChange={e=>set("endDate",e.target.value)}/></label><label className={s.wide}><span><input type="checkbox" checked={form.allDay} onChange={e=>set("allDay",e.target.checked)}/> ทั้งวัน</span></label>{!form.allDay&&<><label>เวลาเริ่ม<input required type="time" value={form.start} onChange={e=>set("start",e.target.value)}/></label><label>เวลาสิ้นสุด<input required type="time" value={form.end} onChange={e=>set("end",e.target.value)}/></label></>}
 <label>สถานที่<input value={form.location} onChange={e=>set("location",e.target.value)}/></label><label>ผู้รับผิดชอบ / ผู้เข้าร่วม<input value={form.owner} onChange={e=>set("owner",e.target.value)}/></label><label className={s.wide}>ค้นหาหนังสือในระบบ<input value={docSearch} placeholder="ค้นหาชื่อเรื่องหรือเลขหนังสือ" onChange={e=>setDocSearch(e.target.value)}/><select value={form.documentId} onChange={e=>set("documentId",e.target.value)}><option value="">ไม่เชื่อมหนังสือ</option>{documents.filter(d=>d.id===form.documentId||normalized(d.subject+" "+d.number).includes(normalized(docSearch))).map(d=><option key={d.id} value={d.id}>{d.number} {d.subject}</option>)}</select></label>
 <div className={s.wide}><strong>แนบลิงก์ไฟล์ / Google Drive</strong><p>เชื่อมไฟล์ที่มีอยู่ ไม่สร้างสำเนาหรือเปลี่ยนสิทธิ์การเข้าถึง</p>{form.attachments.map((a,i)=><div className={s.attachment} key={i}><input required aria-label={`ชื่อไฟล์ ${i+1}`} placeholder="ชื่อไฟล์" value={a.name} onChange={e=>set("attachments",form.attachments.map((v,j)=>i===j?{...v,name:e.target.value}:v))}/><input required type="url" aria-label={`ลิงก์ไฟล์ ${i+1}`} placeholder="https://drive.google.com/…" value={a.url} onChange={e=>set("attachments",form.attachments.map((v,j)=>i===j?{...v,url:e.target.value}:v))}/><button type="button" onClick={()=>set("attachments",form.attachments.filter((_,j)=>j!==i))}>เอาออก</button></div>)}<button type="button" disabled={form.attachments.length>=10} onClick={()=>set("attachments",[...form.attachments,{name:"",url:""}])}>+ แนบลิงก์ไฟล์</button></div>
 <label className={s.wide}>รายละเอียด / หมายเหตุ<textarea rows={3} value={form.notes} onChange={e=>set("notes",e.target.value)}/></label><button className={`primary ${s.wide}`} type="submit">{pending?"กำลังบันทึก…":"บันทึกนัดหมาย"}</button></fieldset></form></dialog>}
 </main>;
}
